cmd:
  msg:
    start: Бот запущен! Для подробной информации наберите /help
    unknown: Неизвестная команда!
    help: | 
      Для просмотра добавленных задач наберите /tasks
      
      Для добавления напоминания введите его в полном формате:
          "dd.MM.yyyy HH.mm <Текст>"
      Либо без даты (напоминание на текущую дату):
          "HH.mm <Текст>"
      Либо без времени (напоминание на день, время по-умолчанию - 10.00):
          "dd.MM.yyyy <Текст>"